name: Generate MDs (Rust)

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      README_STATS: "https://github-readme-stats.vercel.app/api/top-langs?username=caoancap&hide_title=true&hide=html,css&langs_count=8&exclude_repo=Java-Random-Stuff,C-Random-Stuff,GLAE,Opcao-MpC"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout md-fuse
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        repository: caoancap/md-fuse
    - name: Checkout base files
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        repository: caoancap/readme-base
        path: out
        sparse-checkout: |
          files
          md.conf.json
    - name: Organize folders
      run: |
           cp -r ./out/* ./
           rm -rf ./out/files
           rm -f ./out/md.conf.json
    - name: Download Charts
      run: |
           curl -o ./out/top-languages.svg "${{env.README_STATS}}"
           curl -o ./out/top-languages-dark.svg "${{env.README_STATS}}&theme=tokyonight"
    - name: Run
      run: |
           export VERSION=$(date +'%Y%m%d%H%M%S')
           cargo run
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        folder: out
        clean: false
