name: Generate MDs (Python)

on:
  schedule:
    - cron: "0 2,5,23 * * *"
  workflow_dispatch:

jobs:
  build:
    env:
      README_STATS: "https://github-readme-stats.vercel.app/api/top-langs?username=caoancap&hide_title=true&hide=html,css&langs_count=8"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        cache-prefix: ${{ matrix.python-version }}
    - name: Checkout md-fuse-py
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        repository: caoancap/md-fuse-py
    - name: Checkout base files
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        repository: caoancap/readme-base
        path: out
        sparse-checkout: |
          files
          md.conf.json
    - name: Organize folders
      run: |
           cp -r ./out/* ./
           rm -rf ./out/files
           rm -f ./out/md.conf.json
    - name: Download Charts
      run: |
           curl -o ./out/top-languages.svg "${{env.README_STATS}}"
           curl -o ./out/top-languages-dark.svg "${{env.README_STATS}}&theme=tokyonight"
    - name: Sync
      run: rye sync
    - name: Run
      run: |
           export VERSION=$(date +'%Y%m%d%H%M%S')
           rye run fuse
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        folder: out
        clean: false
